config/routes.rb
module StaticPage
  def self.remove_spree_mount_point(path)
    regex = Regexp.new Rails.application.routes.url_helpers.spree_path
    path.sub( regex, '').split('?')[0]
  end
end

class Spree::StaticPage
  def self.matches?(request)
    slug = StaticPage::remove_spree_mount_point(request.fullpath)
    pages = Spree::Page.arel_table
    Spree::Page.visible.by_slug(slug).exists?
  end
end

class Spree::StaticRoot
  def self.matches?(request)
    path = StaticPage::remove_spree_mount_point(request.fullpath)
    path.nil? && Spree::Page.visible.by_slug(path.to_s).first
  end
end

Spree::Core::Engine.routes.prepend do

  namespace :admin do
    resources :pages do
      delete 'attachment/:attachment_id' => 'pages#attachment', :as => "delete_attachment"
    end
  end

  constraints(Spree::StaticRoot) do
    match '/', :to => 'static_content#show', :via => :get, :as => 'static'
  end

  constraints(Spree::StaticPage) do
    match '/*path', :to => 'static_content#show', :via => :get, :as => 'static'
  end
end

app/models/spree/page.rb
class Spree::Page < ActiveRecord::Base
  default_scope :order => "position ASC"
  has_many :attachments, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true

  validates_presence_of :title
  validates_presence_of [:slug, :body], :if => :not_using_foreign_link?
  validates_presence_of :layout, :if => :render_layout_as_partial?

  scope :visible, where(:visible => true)
  scope :header_links, where(:show_in_header => true).visible
  scope :footer_links, where(:show_in_footer => true).visible
  scope :sidebar_links, where(:show_in_sidebar => true).visible

  before_save :update_positions_and_slug

  # attr_accessible :file,:attachments_attributes, :title, :slug, :body, :meta_title, :meta_keywords, :meta_description, :layout, :foreign_link, :position, :show_in_sidebar, :show_in_header, :show_in_footer, :visible, :render_layout_as_partial

  def self.by_slug(slug)
    slug = StaticPage::remove_spree_mount_point(slug)
    pages = self.arel_table
    query = pages[:slug].eq(slug).or(pages[:slug].eq("/#{slug}"))
    self.where(query)
  end

  def initialize(*args)
    super(*args)

    last_page = Spree::Page.last
    self.position = last_page ? last_page.position + 1 : 0
  end

  def link
    foreign_link.blank? ? slug : foreign_link
  end

private

  def update_positions_and_slug
    unless new_record?
      return unless prev_position = Spree::Page.find(self.id).position
      if prev_position > self.position
        Spree::Page.update_all("position = position + 1", ["? <= position AND position < ?", self.position, prev_position])
      elsif prev_position < self.position
        Spree::Page.update_all("position = position - 1", ["? < position AND position <= ?", prev_position,  self.position])
      end
    end

    return true
  end

  def not_using_foreign_link?
    foreign_link.blank?
  end
end

app/controllers/spree/admin/pages_controller.rb
class Spree::Admin::PagesController < Spree::Admin::ResourceController


  def attachment
    @attachment = Attachment.find(params[:attachment_id])
    @attachment.destroy
    render :js => "$('span##{params[:attachment_id]}').hide()"
  end  
end

app/controllers/spree/static_content_controller.rb
class Spree::StaticContentController < Spree::StoreController

  helper "spree/products"
  layout :determine_layout

  def show
    path = case params[:path]
    when Array
      '/' + params[:path].join("/")
    when String
      '/' + params[:path]
    when nil
      request.path
    end

    unless @page = Spree::Page.visible.by_slug(path).first
      render_404
    end
  end

  private

  def determine_layout
    return @page.layout if @page and @page.layout.present? and not @page.render_layout_as_partial?
    Spree::Config.layout
  end

  def accurate_title
    @page ? (@page.meta_title.present? ? @page.meta_title : @page.title) : nil
  end

end

app/helpers/spree/pages_helper.rb
module Spree::PagesHelper
  def render_snippet(slug)
    page = Spree::Page.by_slug(slug).first
    raw page.body if page
  end
end

app/views/spree/admin/pages/_attachment_fields.html.erb
_attachment_fields.html.erb

app/views/spree/admin/pages/_form.html.erb
<div class="row">
  <div class="alpha ten columns">
    <%= f.field_container :title do %>
      <%= f.label :title %> <span class="required">*</span><br />
      <%= f.text_field :title, :class => 'fullwidth title' %>
      <%= f.error_message_on :title %>
    <% end %>

    <%= f.field_container :slug do %>
      <%= f.label :slug %> <span class="required">*</span><br />
      <%= f.text_field :slug, :class => 'fullwidth title' %>
      <%= f.error_message_on :slug %>
    <% end %>

    <%= f.field_container :body do %>
      <%= f.label :body %><span class="required">*</span><br />
      <%= f.text_area :body, {:class => 'fullwidth'} %>
      <%= f.error_message_on :body %>
    <% end %>
<div id="image_attachments">
          <% @page.attachments.each do |atta| %>
            <%= content_tag_for :span, atta do %>


            <% if atta.file_content_type =~ /image.*/ %>
              <%= image_tag atta.file.url(:thumb) %>
            <% else %>
              <%= link_to atta.file_file_name, atta.file.url %>
            <% end %>
            <%= link_to image_tag('/assets/admin/cross.png'), admin_page_delete_attachment_path(@page,atta),
                  :confirm => 'Are you sure?', :method => :delete, :remote => true %>
            <%# link_to_function image_tag('admin/cross.png'), "remove_fields(this)" %>
              <% end %>
        <% end %>
        </div>
      <span id="attachments">

      </span>
      <br>
      <a href="#" id="agregar_adjunto" class="page"><img src="/assets/admin/add_16.png" alt="Add File">Add File</a>
      <br><br>


       <script type="text/x-handlebars-template" id="attachmentTemplate">
          <span class="fields">
            <div class="field file optional">
              <label class="file optional" for="{{clase}}_attachments_attributes_{{numero}}_file">
               File
              </label>
              <input class="file optional" id="{{clase}}_attachments_attributes_{{numero}}_file" name="{{clase}}[attachments_attributes][{{numero}}][file]" type="file">
            </div>
          </span>
        </script>
    <script type="text/javascript">

    $(document).ready(function() {
      var attachment_numero = $("#attachments input.hidden").size();

      var source = $("#attachmentTemplate").html();
      if (source) {
        var template = Handlebars.compile(source);
      };

      $('#agregar_adjunto').click(function(e) {
        var clase = $(this).attr('class');
        e.preventDefault();
        $("#attachments").append(template({ "numero": attachment_numero, "clase": clase }));
        attachment_numero++;
      });

      $(".collections .open").click(function(e) {
        e.preventDefault();
        $("ul.sub").hide();
        $(this).next().next().slideDown();
      });

      $("#pictures a").hover(
        function() {
          $(this).find('div').fadeIn('fast');
        },
        function() {
          $(this).find('div').fadeOut();
        }
      );




    });

    function remove_fields(link) {
        $(link).prev("input[type=hidden]").val("1");
        $(link).closest(".fields").hide();
    };
    </script>


  </div>
  
  <div class="omega six columns">
    <%= f.field_container :meta_title do %>
      <%= f.label :meta_title %><br />
      <%= f.text_field :meta_title, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_title %>
    <% end %>

    <%= f.field_container :meta_keywords do %>
      <%= f.label :meta_keywords %><br />
      <%= f.text_field :meta_keywords, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_keywords %>
    <% end %>

    <%= f.field_container :meta_description do %>
      <%= f.label :meta_description %><br />
      <%= f.text_field :meta_description, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_description %>
    <% end %>
    
    <%= f.field_container :layout do %>
      <%= f.label :layout %><br />
      <%= f.text_field :layout, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :foreign_link do %>
      <%= f.label :foreign_link %><br />
      <%= f.text_field :foreign_link, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :position do %>
      <%= f.label :position %><br />
      <%= f.number_field :position, :min => 0 %>
    <% end %>

    <ul id="static_page_options">
      <li>
        <%= f.check_box :show_in_sidebar %>
        <%= f.label :show_in_sidebar %>
      </li>
      <li>
        <%= f.check_box :show_in_header %>
        <%= f.label :show_in_header %>
      </li>
      <li>
        <%= f.check_box :show_in_footer %>
        <%= f.label :show_in_footer %>
      </li>
      <li>
        <%= f.check_box :visible %>
        <%= f.label :visible %>
      </li>
      <li>
        <%= f.check_box :render_layout_as_partial %>
        <%= f.label :render_layout_as_partial %>
      </li>
    </ul>

  </div>
</div>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
   <%= t("static_content.static_pages") %> <i class="icon-arrow-right"></i> <%= t("static_content.editing_page") %> "<%= @page.title%>"
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_static_pages_list), spree.admin_pages_url, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render "spree/shared/error_messages", :target => @page %>

<%= form_for [:admin, @page],:html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_actions do %>  
  <li><%= button_link_to t("static_content.new_page"), new_object_url, :icon => 'icon-plus' %></li>
<% end %>

<% content_for :page_title do %>
   <%= t("static_content.static_pages") %>
<% end %>

<table class="index">
  <colgroup>
    <col style="width: 40%" />
    <col style="width: 40%" />
    <col style="width: 10%" />
    <col style="width: 10%" />
  </colgroup>
  <thead>
    <tr>
      <th><%= Spree::Page.human_attribute_name(:title) %></th>
      <th><%= t("static_content.link") %></th>
      <th><%= Spree::Page.human_attribute_name(:visible) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @pages.each do |page| %>
      <tr class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
        <td>
          <%= page.title %>
        </td>
        <td>
          <%= link_to page.link, page.link, :target => '_blank' %>
        </td>
        <td class="align-center">
          <%= content_tag(:i, '', :class => 'icon-ok green') if page.visible %>
        </td>
        <td  class="actions">
          <%= link_to_edit page, :no_text => true %>
          <%= link_to_delete page, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
   <%= t("static_content.static_pages") %> <i class="icon-arrow-right"></i> <%= t("static_content.new_page") %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_static_pages_list), spree.admin_pages_url, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render "spree/shared/error_messages", :target => @page %>

<%= form_for [:admin, @page],:html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/static_content/_static_content_footer.html.erb
<nav id="footer-pages">
  <ul><%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.visible.footer_links, :as => :page %></ul>
</nav>

app/views/spree/static_content/_static_content_header.html.erb
<%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.visible.header_links, :as => :page %>

app/views/spree/static_content/_static_content_list.html.erb
<% if page.foreign_link.present? %>
  <li class='not'><%= link_to page.title, page.foreign_link, {:target => "_blank"} %></li>
<% else %>
  <% page_uri = Rails.application.routes.named_routes[:spree].path.spec.to_s == '/' ? page.slug : Rails.application.routes.named_routes[:spree].path.spec.to_s + page.slug %>
  <li class=<%=(request.fullpath.gsub('//','/') == page_uri) ? 'current' : 'not'%>><%= link_to page.title, page_uri  %></li>
<% end %>

app/views/spree/static_content/_static_content_sidebar.html.erb
<% if Spree::Page.visible.sidebar_links.any? %>
<nav id="sidebar-pages-menu" class="sidebar-item">
  <h6 class="page-navigation-title"><%= t("static_content.page_navigation_title")%></h6>
  <ul><%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.visible.sidebar_links, :as => :page %></ul>
</nav>
<% end %>

app/views/spree/static_content/show.html.erb
<% if @page.layout.present? and @page.render_layout_as_partial? %>
  <%= render :partial => @page.layout %>
<% else %>
  <% content_for :head do -%>
    <%- if @page.meta_title.present? -%>
      <meta name="title" content="<%=@page.meta_title%>">
    <%- else -%>
      <meta name="title" content="<%=@page.title%>">
    <%- end -%>
    <meta name="keywords" content="<%=@page.meta_keywords%>">
    <meta name="description" content="<%=@page.meta_description%>">
  <% end -%>

  <% content_for :sidebar do %>
    <% if "products" == @current_controller && @taxon %>
      <%= render :partial => "spree/shared/filters" %>
    <% else %>
      <%= render :partial => "spree/shared/taxonomies" %>
    <% end %>
  <% end %>

  <h1><%= @page.title %></h1>
  <div id="page_content">
    <%= raw @page.body %>
    <%= render '/shared/static' %>
  </div>
<% end %>